### ISSUE TITLE
Slider Problem

### ISSUE THREAD

**Issue by Bl4cksh4rk1990** [ioBroker/ioBroker.vis-metro#12]
Hello,
when i have more than one view in my project, the slider from the heating widget only works in the first opened view. In all other views the slider doesn't move anymore.

**Comment by DutchmanNL** [comment]
i experience an equal issue together with  LJSven, see 
"https://forum.iobroker.net/viewtopic.php?f=30&t=13738&p=145714#p145714"

- When the page loads first time the slider is at zero, but the set value is visible to be higher
- reloading the page moves the slider to the proper position
- moving the slider changes the set value as expected

**Comment by DutchmanNL** [comment]
edit : screenshots add

First load :
![screen shot 2018-04-26 at 16 11 42](https://user-images.githubusercontent.com/7318445/39311285-d1342012-496c-11e8-903b-0786325380a8.png)

After hitting the refresh button :
![screen shot 2018-04-26 at 16 11 52](https://user-images.githubusercontent.com/7318445/39311286-d15426fa-496c-11e8-8b2d-f7464fe94868.png)

**Comment by Blubb98321** [comment]
I got the same Problem, only when I refresh the site with the sliders, they will work correctly. So when I navigate from my home screen to the site with the sliders, they will stuck...

![homescreen](https://user-images.githubusercontent.com/54849472/64176903-a448e880-ce5e-11e9-8ea8-fb97cf182a43.png)
to
![music_screen](https://user-images.githubusercontent.com/54849472/64176946-b9be1280-ce5e-11e9-8850-532a8afabdd0.png)
--> Slider gets stuck...


After reloading:
![music_screen_reloaded](https://user-images.githubusercontent.com/54849472/64176991-d3f7f080-ce5e-11e9-94ea-3356df48d047.png)


Thanks for all help

**Comment by bassbumper** [comment]
Found out that there is an issue getting the slider length because the element size is set to AUTO. It cannot calculate the length in pixel in that case.
Quick fix for me: set a fix width for the slider in the CSS file. This solved all issues

**Comment by MeinzIsAs** [comment]
@bassbumper Can you tell us how you`ve changed the width in the css file?

**Comment by JulianFu** [comment]
Hey there, as I just got the same problem, following is the solution described by @bassbumper 👍 

go to your view, select one of the metro widgets you want to change (you only need one in this solution, it will work for the complete view)
Open properties > CSS and add

`.metro .slider {
       width: 263px !important;
}`

This is a solution, but not a nice one - as we are overriding the CSS from the metro creator.
But it works.
