### ISSUE TITLE
min/max values widgets with sliders

### ISSUE THREAD

**Issue by Pmant** [ioBroker/ioBroker.vis-metro#2]
Aufgefallen ist es mir bisher bei dem heating widget und dem dimmer widget.
Bei ersterem bleibt min anscheinend bei 0 kleben, wenn man z. B. nur einen Bereich von 12-30 °C erlauben will, steht der slider bei 12 grad trotzdem ca. in der Mitte, da links 0 bleibt.
Bei dem dimmer widget wollte ich 0-254 erlauben, rechts bleibt aber 100, man kann also höchstens einen Wert von 100 erreichen. Auch hier bleibt links immer 0.

**Comment by Pmant** [comment]
metro.js line 502:
```
o.max = o.max > 100 ? 100 : o.max;
```
Wird diese Einschränkung für irgendetwas gebraucht? Ein erster Test hat bei mir ergeben, dass das Widget ohne diese Einschränkung trotzdem gut funktioniert.

**Comment by GermanBluefox** [comment]
Konnte ich reproduzieren. Danke

**Comment by Pmant** [comment]
funktioniert jetzt besser, ich komme mit dem Slider aber nur auf maximal 253.99999999999997 statt 254 (chrome). Der switch beim Dimmer Tile geht allerdings noch immer bei 100 auf "ON".

**Comment by GermanBluefox** [comment]
Es geht nicht bei 100 auf ON sondern wenn das Wert > 127 (die Hälfte)
Um 253.99999999999997 zu vermeiden muss man Step 1 machen.

**Comment by Pmant** [comment]
Ah okay, das erklärt einiges. Danke!
