### ISSUE TITLE
heating tile

### ISSUE THREAD

**Issue by Pmant** [ioBroker/ioBroker.vis-metro#3]
Das kleine Fenster-offen Icon unten rechts im Tile ist super, allerdings wird dieses nie aktualisiert. Erst wenn ich den View im Browser neu lade, wird der aktuelle Zustand angezeigt. Die Soll-Temperatur wird beim öffnen/schließen des Fensters korrekt aktualisiert.

**Comment by GermanBluefox** [comment]
Sollte in der neuen Version gehen

**Comment by Pmant** [comment]
fixed. Musste vis und web neustarten um die neue Version auch im view zu haben.
