### ISSUE TITLE
Navigation Tile Brand

### ISSUE THREAD

**Issue by Pmant** [ioBroker/ioBroker.vis-metro#4]
Brand Background wird nicht angezeigt, sobald Brand Background inactive und Brand Background active den selben Wert haben.
Widget export:
```javascript
[{"tpl":"tplMetroTileNav","data":{"visibility-cond":"==","visibility-val":1,"hover":"true","transform":"true","label":"Navigation","bg_class":"bg-indigo","bg_class_active":"bg-magenta","badge_bg_class":"bg-cyan","badge_bg_class_active":"bg-teal","icon_badge":"icon-file","brand_bg_class":"bg-black","brand_bg_class_active":"bg-black","icon_class":"icon-new"},"style":{"left":"146px","top":"319px"},"widgetSet":"metro"}]
```
Nur der Navigation Tile hat diesen Bug

**Comment by GermanBluefox** [comment]
Danke. Erledigt in der neuen Version. Bitte testen und Issue zumachen.

**Comment by Pmant** [comment]
Musste .web noch manuell neustarten, damit die neuen Tiles geladen werden, der Fehler wurde mit dem Update behoben.
