### ISSUE TITLE
Missing badge icon at val.list tile

### ISSUE THREAD

**Issue by buanet** [ioBroker/ioBroker.vis-metro#7]
Hallo,
beim val.list tile (ValueList 8) wird kein Badge Icon angezeigt (Abzeichenikone).

Ich weiß nicht ob es alles ist, aber beim "studieren" der metro.html ist mir aufgefallen, dass dort das `<i>`-Tag fehlt.

`<div class="badge <%= this.data.attr('badge_bg_class' + vis.binds.metro.format(vis.states.attr(this.data.attr('oid') + '.val'), 10)) %>"></i></div>`

MfG,
André

**Comment by GermanBluefox** [comment]
Bitte checken: https://github.com/ioBroker/ioBroker.vis-metro/commit/5414bc0a7f09ef249fa3cb3afbefe964d6df4aad

**Comment by buanet** [comment]
Läuft!
Besten Dank. 

MfG,
André
